// 中文/常见项目领域词 → GitHub 英文搜索关键词词典
// 用于把"我要做一个X舆情监控"转换成 github 能搜的英文关键词

export const DICT: Record<string, string[]> = {
  舆情: ['sentiment', 'social listening', 'opinion', 'monitoring'],
  监控: ['monitoring', 'monitor', 'dashboard'],
  采集: ['crawler', 'scraper', 'collector', 'ingest'],
  爬虫: ['crawler', 'scraper', 'spider'],
  推特: ['twitter', 'x api'],
  微博: ['weibo'],
  商城: ['ecommerce', 'shop', 'mall', 'commerce'],
  电商: ['ecommerce', 'commerce', 'shop'],
  聊天: ['chat', 'messenger', 'im', 'realtime chat'],
  客服: ['customer service', 'support ticket', 'helpdesk'],
  简历: ['resume', 'cv builder'],
  表单: ['form builder', 'form'],
  审批: ['approval', 'workflow'],
  低代码: ['low-code', 'lowcode', 'no-code'],
  管理后台: ['admin dashboard', 'admin panel', 'admin'],
  后台: ['admin', 'backend'],
  仪表盘: ['dashboard'],
  打卡: ['attendance', 'check-in'],
  考勤: ['attendance'],
  抽奖: ['lucky draw', 'raffle', 'lottery', 'spin wheel'],
  投票: ['voting', 'poll'],
  分享: ['share', 'social share', 'share card'],
  图片: ['image', 'picture', 'image processing'],
  视频: ['video', 'video player', 'streaming'],
  音频: ['audio', 'music player'],
  编辑器: ['editor'],
  富文本: ['rich text', 'wysiwyg', 'markdown editor'],
  协同: ['collaboration', 'collaborative', 'realtime editing'],
  文档: ['document', 'docs', 'wiki'],
  笔记: ['notes', 'notebook', 'note taking'],
  日历: ['calendar', 'scheduling'],
  任务: ['task', 'todo', 'task management'],
  待办: ['todo', 'task'],
  项目管理: ['project management', 'project tracker'],
  推送: ['push notification', 'notification', 'web push'],
  短信: ['sms'],
  支付: ['payment', 'pay', 'checkout'],
  登录: ['authentication', 'auth', 'login', 'oauth'],
  权限: ['permission', 'rbac', 'access control', 'authorization'],
  数据可视化: ['data visualization', 'visualization', 'charts'],
  图表: ['charts', 'chart'],
  报表: ['report', 'analytics', 'bi'],
  搜索: ['search', 'full-text search'],
  推荐: ['recommendation', 'recommender', 'recommendation system'],
  人工智能: ['ai', 'artificial intelligence'],
  大模型: ['llm', 'large language model', 'gpt', 'chatgpt'],
  模型: ['model', 'ml'],
  代理: ['proxy', 'agent'],
  助手: ['assistant', 'agent'],
  ai: ['ai', 'llm', 'agent', 'chatbot'],
  agent: ['agent', 'ai agent'],
  游戏: ['game', 'web game'],
  音乐: ['music'],
  直播: ['live streaming', 'livestream', 'live'],
  点餐: ['food ordering', 'ordering'],
  外卖: ['food delivery', 'delivery'],
  打车: ['ride hailing', 'taxi'],
  地图: ['map', 'gis', 'mapping'],
  定位: ['location', 'geolocation'],
  天气: ['weather'],
  翻译: ['translation', 'translator'],
  语音: ['speech', 'voice', 'asr', 'tts'],
  识别: ['recognition', 'ocr'],
  生成: ['generator', 'generation', 'generate'],
  自动化: ['automation'],
  定时: ['scheduler', 'cron', 'scheduling', 'job'],
  消息队列: ['message queue', 'mq', 'kafka', 'rabbitmq'],
  缓存: ['cache', 'redis'],
  数据库: ['database', 'db', 'sql', 'orm'],
  框架: ['framework'],
  组件库: ['component library', 'ui components', 'design system'],
  图标: ['icons', 'icon'],
  可视化: ['visualization', 'visual'],
  克隆: ['clone'],
  仿: ['clone'],
  头像: ['avatar'],
  名片: ['business card', 'profile card'],
  弹幕: ['danmaku', 'bullet screen'],
  截图: ['screenshot', 'capture'],
  二维码: ['qrcode', 'qr code'],
  文件: ['file', 'file upload', 'file manager'],
  上传: ['upload', 'file upload'],
  下载: ['download'],
  邮件: ['email', 'mail'],
  分析: ['analytics', 'analysis'],
  统计: ['statistics', 'stats', 'analytics'],
  追踪: ['tracking', 'tracker'],
  日志: ['logging', 'logger', 'log'],
  性能: ['performance', 'perf'],
  测试: ['testing', 'test', 'e2e'],
  部署: ['deployment', 'deploy', 'ci', 'cd'],
  脚手架: ['scaffold', 'boilerplate', 'starter'],
  模板: ['template', 'starter', 'boilerplate'],
  博客: ['blog', 'blog engine'],
  论坛: ['forum', 'discussion'],
  社区: ['community', 'social network'],
  社交: ['social', 'social network'],
  招聘: ['recruitment', 'job board', 'hiring'],
  求职: ['job', 'recruitment'],
  问卷: ['survey', 'questionnaire'],
  签到: ['check-in', 'sign-in'],
  积分: ['points', 'rewards', 'gamification'],
  会员: ['membership', 'subscription', 'paywall'],
  优惠券: ['coupon', 'voucher', 'promotion'],
  团购: ['group buying', 'deal'],
  秒杀: ['flash sale', 'seckill'],
  订单: ['order', 'order management'],
  购物车: ['shopping cart', 'cart'],
  商品: ['product', 'catalog'],
  股票: ['stock', 'trading', 'finance'],
  加密货币: ['crypto', 'cryptocurrency', 'blockchain'],
  区块链: ['blockchain', 'web3'],
  钱包: ['wallet', 'payment'],
  记账: ['bookkeeping', 'ledger', 'expense tracker'],
  教育: ['education', 'elearning', 'lms'],
  课程: ['course', 'lms', 'learning platform'],
  考试: ['exam', 'quiz', 'assessment'],
  面试: ['interview', 'interview questions'],
  视频会议: ['video conference', 'meeting', 'webrtc'],
  会议: ['meeting', 'conference'],
  白板: ['whiteboard', 'canvas'],
  流程图: ['flowchart', 'diagram'],
  思维导图: ['mindmap', 'mind map'],
  设计: ['design', 'figma'],
  演示: ['slides', 'presentation', 'reveal'],
  ppt: ['slides', 'presentation', 'reveal'],
  表格: ['spreadsheet', 'excel', 'table'],
  pdf: ['pdf', 'pdf generator'],
  压缩: ['compress', 'compression'],
  加密: ['encryption', 'crypto', 'encode'],
  短链接: ['url shortener', 'short link'],
  websocket: ['websocket', 'socket'],
  实时: ['realtime', 'real-time', 'live'],
  离线: ['offline', 'pwa'],
  暗黑: ['dark mode', 'dark theme'],
  主题: ['theme', 'theming'],
  国际化: ['i18n', 'internationalization'],
  多语言: ['i18n', 'multi-language', 'translation'],
  无障碍: ['accessibility', 'a11y'],
  移动端: ['mobile', 'mobile web', 'responsive'],
  h5: ['h5', 'mobile web', 'mobile'],
  小程序: ['miniprogram', 'mini program', 'wechat'],
  跨端: ['cross-platform', 'react native', 'flutter'],
  桌面: ['desktop', 'electron', 'tauri'],
  服务器: ['server', 'node'],
  云: ['cloud', 'saas'],
  微服务: ['microservice', 'microservices'],
  容器: ['docker', 'container', 'kubernetes'],
  代码生成: ['code generation', 'codegen'],
  文档生成: ['documentation generator', 'docs'],
  静态站点: ['static site generator', 'ssg'],
  seo: ['seo', 'meta'],
  落地页: ['landing page', 'landing'],
  活动页: ['landing page', 'campaign', 'h5'],
  营销: ['marketing', 'campaign'],
  裂变: ['referral', 'viral', 'invite'],
  排行榜: ['leaderboard', 'ranking'],
  弹窗: ['modal', 'dialog', 'popup'],
  轮播: ['carousel', 'slider'],
  瀑布流: ['masonry', 'waterfall'],
  图片压缩: ['image compression', 'compress image'],
  图片裁剪: ['image crop', 'cropper'],
  表情: ['emoji', 'sticker'],
  拖拽: ['drag and drop', 'dnd'],
  排序: ['sortable', 'sort'],
  状态管理: ['state management', 'zustand', 'redux'],
  路由: ['router', 'routing'],
  动画: ['animation', 'motion', 'transition'],
  无限滚动: ['infinite scroll', 'virtual scroll'],
  虚拟列表: ['virtual list', 'virtual scroll'],
  数据表格: ['data table', 'table', 'datatable'],
  时间选择: ['date picker', 'time picker'],
  日期: ['date', 'date picker', 'calendar'],
  倒计时: ['countdown', 'timer'],
  验证码: ['captcha', 'verification code'],
  单点登录: ['sso', 'single sign-on'],
  订阅: ['subscription', 'recurring billing'],
  评论: ['comment', 'comments system'],
  点赞: ['like', 'reaction'],
  收藏: ['favorite', 'bookmark', 'collection'],
  关注: ['follow', 'social graph'],
  好友: ['friends', 'social'],
  群组: ['group', 'chat room'],
  私信: ['private message', 'dm'],
  定时任务: ['cron', 'scheduler', 'job scheduler'],
  任务队列: ['task queue', 'job queue', 'bull'],
  工作流: ['workflow', 'state machine'],
  分页: ['pagination'],
  提示: ['toast', 'notification', 'tooltip'],
  主题切换: ['theme switcher', 'dark mode'],
  图片查看: ['image viewer', 'lightbox', 'gallery'],
  图片编辑: ['image editor', 'photo editor'],
  文字识别: ['ocr', 'text recognition'],
  语音识别: ['speech recognition', 'asr', 'whisper'],
  语音合成: ['text to speech', 'tts'],
  字幕: ['subtitle', 'srt', 'caption'],
  视频剪辑: ['video editor', 'video editing'],
  视频播放: ['video player'],
  音乐播放: ['music player'],
  文件传输: ['file transfer', 'file share'],
  云存储: ['cloud storage', 'object storage', 's3'],
  备份: ['backup', 'restore'],
  同步: ['sync', 'synchronization'],
  用户系统: ['user management', 'user system', 'auth'],
  注册: ['registration', 'signup', 'sign up'],
  限流: ['rate limit', 'rate limiting', 'throttle'],
  网关: ['api gateway', 'gateway'],
  鉴权: ['authentication', 'jwt', 'auth'],
  认证: ['authentication', 'auth'],
  jwt: ['jwt', 'auth'],
  oauth: ['oauth', 'oauth2'],
  反爬: ['anti-crawler', 'anti-bot'],
  数据清洗: ['data cleaning', 'data processing', 'etl'],
  数据分析: ['data analysis', 'analytics', 'pandas'],
  数据处理: ['data processing', 'etl'],
  机器学习: ['machine learning', 'ml'],
  深度学习: ['deep learning', 'dl', 'pytorch'],
  向量: ['vector', 'embedding'],
  向量数据库: ['vector database', 'embeddings', 'faiss'],
  rag: ['rag', 'retrieval augmented'],
  提示词: ['prompt', 'prompt engineering'],
  多模态: ['multimodal'],
  人脸识别: ['face recognition', 'face detection'],
  智能客服: ['chatbot', 'customer service', 'support bot'],
  数据大屏: ['data screen', 'big screen', 'data visualization'],
  运维: ['devops', 'operation', 'sre'],
  监控系统: ['monitoring', 'alerting', 'grafana'],
  告警: ['alerting', 'alert', 'alarm'],
  日志分析: ['log analysis', 'log analytics', 'elk'],
  链路追踪: ['distributed tracing', 'trace', 'opentelemetry'],
  埋点: ['analytics', 'tracking', 'event tracking'],
  用户行为: ['user behavior', 'event tracking', 'analytics'],
  ab测试: ['a/b testing', 'ab testing', 'experiment'],
  功能开关: ['feature flag', 'feature toggle'],
  配置中心: ['config center', 'configuration'],
  容器编排: ['kubernetes', 'k8s', 'container orchestration'],
  分布式: ['distributed'],
  时序数据: ['time series', 'timeseries', 'influxdb'],
  图数据库: ['graph database', 'neo4j'],
  搜索引擎: ['search engine', 'elasticsearch', 'meilisearch'],
  全文检索: ['full-text search', 'search engine'],
  推荐系统: ['recommendation system', 'recommender'],
  风控: ['risk control', 'fraud detection', 'risk'],
  金融: ['finance', 'fintech', 'trading'],
  报销: ['reimbursement', 'expense'],
  发票: ['invoice', 'receipt'],
  看板: ['kanban', 'board'],
  甘特图: ['gantt', 'gantt chart'],
  习惯打卡: ['habit tracker'],
  okr: ['okr', 'goal'],
  kpi: ['kpi', 'metrics'],
  考试系统: ['exam system', 'quiz platform'],
  电子书: ['ebook', 'epub', 'reader'],
  阅读: ['reading', 'reader', 'epub'],
  壁纸: ['wallpaper'],
  相册: ['gallery', 'album', 'photo'],
  短视频: ['short video', 'shorts'],
  播客: ['podcast'],
  健身: ['fitness', 'gym', 'workout'],
  旅行: ['travel', 'trip planner'],
  酒店: ['hotel', 'booking'],
  民宿: ['homestay', 'bnb'],
  机票: ['flight', 'airline', 'booking'],
  二手: ['second-hand', 'resale', 'marketplace'],
  租赁: ['rental', 'rent'],
  二手房: ['real estate', 'property'],
  租房: ['rental', 'apartment'],
  房产: ['real estate', 'property'],
  菜谱: ['recipe', 'cooking'],
  美食: ['food', 'recipe'],
  餐厅: ['restaurant'],
  物联网: ['iot', 'internet of things'],
  智能家居: ['smart home', 'home automation'],
  机器人: ['robot', 'robotics'],
  物流: ['logistics', 'delivery', 'shipping'],
  快递: ['express', 'parcel', 'shipping'],
  供应链: ['supply chain'],
  零售: ['retail', 'pos'],
  内容管理: ['cms', 'content management'],
  新闻: ['news', 'rss'],
  阅读器: ['reader', 'rss reader'],
  书签: ['bookmark', 'pocket'],
  知识库: ['knowledge base', 'wiki'],
  知识管理: ['knowledge management', 'wiki', 'notes'],
  个人主页: ['personal website', 'portfolio', 'homepage'],
  个人博客: ['blog', 'personal blog'],
  第二大脑: ['second brain', 'pkms', 'notes'],
  时间管理: ['time management', 'pomodoro', 'calendar'],
  专注: ['focus', 'pomodoro', 'deep work'],
  冥想: ['meditation', 'mindfulness'],
  日记: ['diary', 'journal'],
  理财: ['investment', 'finance', 'portfolio'],
  基金: ['fund', 'investment'],
  智能合约: ['smart contract', 'solidity'],
  defi: ['defi', 'decentralized finance'],
  游戏化: ['gamification'],
  成就: ['achievement', 'badge'],
  联机: ['multiplayer', 'online'],
  粒子: ['particles', 'particle effect'],
  物理引擎: ['physics engine', 'physics'],
  游戏引擎: ['game engine'],
  '3d': ['3d', 'three.js', 'webgl'],
  three: ['three.js', '3d', 'webgl'],
  全景: ['panorama', '360'],
  vr: ['vr', 'virtual reality'],
  ar: ['ar', 'augmented reality'],
  数字孪生: ['digital twin'],
  模拟: ['simulation', 'simulator'],
  抠图: ['background removal', 'matting', 'rembg'],
  图片放大: ['image upscale', 'super resolution'],
  老照片修复: ['photo restoration', 'old photo'],
  视频下载: ['video downloader', 'yt-dlp'],
  音频剪辑: ['audio editing', 'audio editor'],
  录音: ['recording', 'recorder'],
  音乐生成: ['music generation', 'musicgen'],
  音乐识别: ['music recognition', 'shazam'],
  有声书: ['audiobook'],
  录屏: ['screen recording', 'screen capture'],
  直播推流: ['live streaming', 'rtmp', 'webrtc'],
  打赏: ['donation', 'tip', 'reward'],
  心理: ['mental health', 'mood'],
  心理测试: ['personality test', 'quiz'],
  mbti: ['mbti', 'personality'],
  职场: ['workplace', 'career'],
  论文: ['paper', 'thesis'],
  查重: ['plagiarism check', 'similarity'],
  数据集: ['dataset'],
  数据标注: ['data annotation', 'labeling'],
  远程: ['remote', 'remote work'],
  自由职业: ['freelance', 'freelancer'],
  问答: ['qa', 'question answer'],
  热点: ['trending', 'hot topics'],
  热搜: ['trending', 'hot search'],
  话题: ['topic', 'hashtag'],
  标签: ['tag', 'hashtag'],
  筛选: ['filter', 'facet'],
  自动补全: ['autocomplete', 'autosuggest'],
  分词: ['tokenizer', 'segmentation', 'jieba'],
  关键词提取: ['keyword extraction', 'tf-idf'],
  摘要: ['summarization', 'summary'],
  文本摘要: ['text summarization'],
  情感分析: ['sentiment analysis'],
  语义: ['semantic', 'nlp'],
  nlp: ['nlp', 'natural language processing'],
  命名实体: ['ner', 'named entity recognition'],
  文本生成: ['text generation', 'generative'],
  对话: ['dialogue', 'conversational'],
  问答系统: ['qa system', 'question answering'],
  知识图谱: ['knowledge graph'],
  多轮对话: ['multi-turn dialogue', 'chatbot'],
  情绪识别: ['emotion recognition', 'sentiment'],
  内容审核: ['content moderation', 'censor'],
  敏感词: ['sensitive words', 'filter'],
  圈子: ['circle', 'community'],
  电子邀请函: ['digital invitation'],
  请柬: ['invitation card', 'wedding invitation'],
  活动报名: ['event registration', 'rsvp'],
  活动管理: ['event management', 'events'],
  票务: ['ticket', 'ticketing'],
  海报: ['poster'],
  海报生成: ['poster generator'],
  封面: ['cover', 'cover image'],
  排版: ['typesetting', 'layout'],
  归因: ['attribution', 'tracking'],
  转化: ['conversion', 'funnel'],
  漏斗: ['funnel', 'conversion funnel'],
  留存: ['retention'],
  增长: ['growth', 'metrics'],
  用户画像: ['user profile', 'persona'],
  人群: ['audience', 'segment'],
  精准营销: ['targeted marketing'],
  个性化: ['personalization', 'recommendation'],
  推荐算法: ['recommendation algorithm'],
  相亲: ['dating', 'matchmaking'],
  交友: ['dating', 'friends'],
  附近的人: ['nearby people', 'geosocial'],
  星座: ['horoscope', 'zodiac'],
  性格: ['personality', 'mbti'],
  简历生成: ['resume generator'],
}

// 提取英文关键词：先匹配词典，再保留输入中已有的英文单词
export function extractKeywords(input: string): string[] {
  const result = new Set<string>()
  const lower = input.toLowerCase()

  // 1. 词典匹配
  for (const [zh, en] of Object.entries(DICT)) {
    if (lower.includes(zh.toLowerCase())) {
      en.forEach((k) => result.add(k))
    }
  }

  // 2. 输入中已有的英文单词（>=3 个字符）
  const enWords = lower.match(/[a-z][a-z0-9+#.-]{2,}/g) || []
  enWords.forEach((w) => result.add(w))

  // 3. 兜底：没有任何关键词时用原文
  if (result.size === 0) {
    input.trim().split(/[\s,，、;；]+/).filter(Boolean).forEach((w) => result.add(w))
  }

  return [...result].slice(0, 12)
}

// 把用户输入转换为 github 搜索 query：关键词 OR 组合，限制在 4 个避免查询过长
export function buildSearchQuery(keywords: string[]): string {
  return keywords.slice(0, 4).join(' OR ')
}

// 相似度打分：repo 与输入关键词的匹配度（name/description/topics 命中）
export function scoreRepo(repo: { name: string; description: string | null; topics: string[] }, keywords: string[]): number {
  const text = [repo.name, repo.description, ...(repo.topics || [])]
    .filter(Boolean)
    .join(' ')
    .toLowerCase()
  let score = 0
  for (const kw of keywords) {
    const k = kw.toLowerCase()
    if (text.includes(k)) score += 1
  }
  return score
}
